apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-local
  namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-local
  template:
    metadata:
      labels:
        app: pod-local
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "while true; do echo 'Current time: ' $(date) >> /shared/data.txt; sleep 5; done"]
          volumeMounts:
            - name: pvc
              mountPath: "/shared"
        - name: multitool
          image: wbitt/network-multitool
          command: ["sh", "-c", "tail -f /shared/data.txt"]
          env:
          - name: HTTP_PORT
            value: "8080"
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: pvc
              mountPath: "/shared"
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: local-pvc
