apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-nfs
  namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool-nfs
  template:
    metadata:
      labels:
        app: multitool-nfs
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          env:
          - name: HTTP_PORT
            value: "8080"
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: pvc
            mountPath: /data/nfs
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: nfs-pvc
