apiVersion: v1
kind: Pod
metadata:
  name: multitool-pod
  namespace: test-1
spec:
  containers:
  - name: multitool-pod
    image: wbitt/network-multitool
    env:
    - name: HTTP_PORT
      value: "1180"
    ports:
    - containerPort: 1180
