apiVersion: v1
kind: Service
metadata:
  name: nginx-init-svc
  namespace: test-2
spec:
  selector:
    app: nginx-init
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
