apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-multitool
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-multitool
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-multitool
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-multitool
    spec:
      containers:
      - name: multitool
        image: "{{ .Values.multitool.image.repository }}:{{ .Values.multitool.image.tag }}"
        imagePullPolicy: {{ .Values.multitool.image.pullPolicy }}
        env:
        - name: HTTP_PORT
          value: "{{ .Values.multitool.httpPort }}"
        ports:
        - containerPort: {{ .Values.multitool.port }}