apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-multitool-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-multitool
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.multitool.service.type }}
  ports:
  - port: {{ .Values.multitool.service.port }}
    targetPort: {{ .Values.multitool.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-multitool