apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-multitool
  namespace: lesson1
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 8080
