apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-nginx-multitool
  namespace: lesson1
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30007
 