apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
  namespace: lesson23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
          - name: html-volume
            mountPath: /usr/share/nginx/html
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: multitool-config
                key: key1
      volumes:
        - name: html-volume
          configMap:
            name: nginx-html-config
