apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: lesson23
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
